services:
  app:
    build: 
      context: ../../..
      dockerfile: ./docker/train/cpu/Dockerfile
    container_name: ag-release-tools
    tty: true
    stdin_open: true
    ports:
      - 80:80
    volumes:
      - ../../../:/code
