services:
  app:
    build: 
      context: ../../..
      dockerfile: ./docker/train/gpu/Dockerfile
    container_name: ag-release-tools
    tty: true
    stdin_open: true
    ports:
      - 80:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ../../../.:/code
